version: "3.8"

services:
  filtering-sample:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    # command: go run cmd/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
    postgres-db: